### ISSUE TITLE
Classnames for Bronze and Platin not usable for scripting

### ISSUE THREAD

**Issue by Andx667** [TacticalTrainingTeam/Modmanagement#8]
"TTT_helmet_bronx_vehiclecrew" should be "TTT_helmet_bronze_vehiclecrew"
"TTT_Vest_Crew_Bronx" => "TTT_Vest_Crew_Bronze"
"TTT_backpack_radio_bronx_us_desert" => "TTT_backpack_radio_bronze_us_desert"

"TTT_Beret_Platinum" and "TTT_backpack_radio_platin_us_desert" should have the same "id" for Platin

**Comment by MenomDE** [comment]
Wurde durch Andx gefixt. Ist im DEV branch und wird heute ins Main geschoben. Repo Update ist am Samstag.
